CREATE DATABASE urban_db;

CREATE TABLE course
(
id INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(200) NOT NULL
);

INSERT INTO course(NAME) VALUES('Java');

UPDATE course SET NAME='Java8' WHERE id=1;

DELETE FROM course WHERE id=1;

SELECT id,NAME FROM course;
